### PR TITLE
Allow symfony/console 5

### PR DESCRIPTION
**Pull request by derrabus**
#SymfonyHackday

### CODE REVIEW

**Comment by derrabus** [comment]
Note: Your Travis build won't actually install `symfony/console` 5.0 until FriendsOfPHP/PHP-CS-Fixer#4608 is resolved. Alternatively, you could remove PHP CS Fixer from `require-dev` to allow the installation of Symfony 5 components on Travis.

**Comment by mnapoli** [comment]
👍  thanks!

Let's wait for https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4608 then

**Comment by tlfbrito** [comment]
@mnapoli php-cs-fixer was merged, and they already release a new tag https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.16.1

**Comment by derrabus** [comment]
I've rebased against master in order to trigger a rebuild on Travis. The php 7.2 run has picked up PHP CS Fixer 2.16.1 and Symfony 5.0 this time.

**Comment by mnapoli** [comment]
Awesome, thank you for taking the time!

**Pull request merged**
